// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcj9Uw3rcenp_Y35iuZetdgEh3MiCWlIs',
    appId: '1:1016858913249:web:b32fbe1344169636b40aa0',
    messagingSenderId: '1016858913249',
    projectId: 'sudoku-flutter-firebase',
    authDomain: 'sudoku-flutter-firebase.firebaseapp.com',
    databaseURL: 'https://sudoku-flutter-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-flutter-firebase.appspot.com',
    measurementId: 'G-67R9VD2DQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHm3AWA_4nw_vQ1Uiov8Ml34pbhK3KdA',
    appId: '1:1016858913249:android:5b91b046f8c0213eb40aa0',
    messagingSenderId: '1016858913249',
    projectId: 'sudoku-flutter-firebase',
    databaseURL: 'https://sudoku-flutter-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgV-LcmNPN01tr6SFucWaFnmnyFKskIvw',
    appId: '1:1016858913249:ios:a3b25cd7f0d9b6deb40aa0',
    messagingSenderId: '1016858913249',
    projectId: 'sudoku-flutter-firebase',
    databaseURL: 'https://sudoku-flutter-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-flutter-firebase.appspot.com',
    androidClientId: '1016858913249-kb5ausli0joqtanh1nas3bffi0fqntsu.apps.googleusercontent.com',
    iosClientId: '1016858913249-5uffqs1b8ati4u73qoslscehg8ngnckb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudokuFlutter',
  );
}
